#!/bin/bash
# German Patch for Philz Recovery
# copyright by thehacker911

# variable Input
string_1=Installing:
string_2=Checking if loki-fying is needed
string_3=Install from sdcard complete.
string_4=Install update from zip file
string_5=Choose zip from
string_6=Choose zip Using Free Browse Mode
string_7=Choose zip from Last Install Folder
string_8=Install zip from sideload
string_9=Install Multiple zip Files
string_10=Setup Free Browse Mode
string_11=Signature Verification
string_12=Verify zip md5sum
string_13=Couldn't open directory
string_14=Failed to close directory.
string_15=No files found.
string_16=Can't mount
string_17=Choose a zip to apply
string_18=Yes - Install
string_19=Confirm install?
string_20=Can't mount
string_20=Choose an image to restore
string_21=Confirm restore?
string_22=Yes - Restore
string_23=Choose a backup to delete
string_24=Yes - Delete
string_25=Confirm delete?
string_26=USB Mass Storage device
string_27=Leaving this menu unmounts
string_28=your SD card from your PC.
string_29=Unmount
string_30=THIS CAN NOT BE UNDONE.
string_31=No
string_32=unknown volume
string_33=can't format_volume
string_34=format_volume failed to unmount
string_35=format_volume: format_rfs_device failed on
string_36=format_volume failed to unmount
string_37=format_volume: no MTD partition
string_38=format_volume: can't open MTD
string_39=format_volume: can't erase MTD
string_40=format_volume: can't close MTD
string_41=format_volume: make_ext4fs failed on
string_42=format_volume: mkfs.f2f2 failed on
string_43=Formatting unknown device.
string_44=No app2sd partition found. Skipping format of /sd-ext.
string_45=Formatting ext3 device.
string_46=Error while unmounting
string_47=Formatting ext2 device.
string_48=Error mounting
string_49=Skipping format...
string_50=Mounts and Storage Menu
string_51=Confirm format?
string_52=Yes - Format
string_53=mount
string_54=unmount
string_55=format
string_56=mount USB storage
string_57=Formatting /data...
string_58=Error formatting
string_59=Done.
string_60=Error unmounting
string_61=Error mounting
string_62=Formatting
string_63=Error formatting
string_64=Done
string_65=Default Backup Format
string_66=Default backup format set to tar
string_67=Default backup format set to dedupe
string_68=Default backup format set to tar + gzip
string_69=Backup to
string_70=Restore from
string_71=Delete from
string_72=Custom Backup to
string_73=Custom Restore from
string_74=Backup and Restore
string_75=Clone ROM to update.zip
string_76=Free Unused Backup Data
string_77=Misc Nandroid Settings
string_78=Unsupported in open source version!
string_79=TWRP backup format must be tar(.gz)!
string_80=Format device
string_81=Confirm formatting?
string_82=Yes - Format device
string_83=Could not format
string_84=Done formatting
string_85=Can't partition device
string_86=Ext Size
string_87=Swap Size
string_88=Partition Type
string_89=Partitioning SD Card... please wait...
string_90=An error occured while partitioning your SD Card. Please see /tmp/recovery.log for more details.
string_91=Can't format unknown volume:
string_92=Can't partition non-vfat:
string_93=Can't partition non mmcblk device:
string_94=Can't partition unsafe device:
string_95=Advanced power options
string_96=Reboot Recovery
string_97=Reboot to Bootloader
string_98=Power Off
string_99=Reboot to Download Mode
string_100=Rebooting recovery...
string_101=Rebooting to
string_102=Shutting down...
string_103=Advanced Menu
string_104=Wipe Dalvik Cache
string_104=Report Error
string_106=Key Test
string_107=Show log
string_108=Partition
string_109=Apply Loki Patch
string_110=Confirm wipe?
string_111=Yes - Wipe Dalvik Cache
string_112=Outputting key codes.
string_113=Go back to end debugging.
string_114=Unable to get recovery.fstab info for %s during fstab generation!
string_115=Unable to create
string_116=Completed outputting fstab.
string_117=Unable process volume! Skipping...
string_118=could not mount
string_119=Checking for ext4 partitions...
string_120=Filesystems need to be converted to ext4.
string_120=A backup and restore will now take place.
string_121=If anything goes wrong, your backup will be
string_122=named %s. Try restoring it
string_123=in case of error.
string_124=ROM may flash stock recovery on boot. Fix?", "Yes - Disable recovery flash"
string_125=Root access possibly lost. Fix?", "Yes - Fix root (/system/bin/su)
string_126=Root access possibly lost. Fix?", "Yes - Fix root (/system/xbin/su)
string_127=Root access is missing. Root device?", "Yes - Root device (/system/xbin/su)

# variable output
message_1=Installation:
message_2=Installation abgebrochen.
message_3=Prüfe loki-fying wird benötigt
message_4=Installieren von SD-Karte komplett.
message_5=Installiere Update von zip-Datei
message_6=Wähle Zip aus
message_7=Wähle Zip aus, mit freien durchsuchen Modus.
message_8=Wähle Zip aus den letzten Installationsordner
message_9=Zip installieren von Sideload
message_10=Installieren einer Multiple ZIP Datei
message_11=Freie Einrichtung des Browsermoduses
message_12=Signaturverifizierung
message_13=Überprüfen der Zip MD5 sum
message_14=Verzeichnis konnte nicht geöffnet werden
message_15=Konnte Verzeichnis nicht schliessen
message_16=Keine Dateien gefunden.
message_17=Kann nicht mounten
message_18=Wähle eine Zip um diese anzuwenden 
message_19=Ja - installieren
message_20=Bestätigen der installation
message_20=Kann nicht mounten
message_21=Wählen Sie ein Backup für die Wiederherstellung.
message_22=Bestätige die Wiederherstellung
message_23=Ja - Wiederherstellen
message_24=Wähle ein Backup das gelöschen werden soll
message_25=Ja - Löschen
message_26=Bestätige das Löschen
message_27=USB Massenspeichergerät
message_28=Verlassen des Menüs
message_29=SD-Karte von Ihrem PC
message_30=Unmount
message_31=Dieses kann nicht rückgängig gemacht werden.
message_32=Nein
message_33=output_string
message_34=output_string
message_35=output_string
message_36=output_string
message_37=output_string
message_38=output_string
message_39=output_string
message_40=output_string
message_41=output_string
message_42=output_string
message_43=output_string
message_44=output_string
message_45=output_string
message_46=output_string
message_47=output_string
message_48=output_string
message_49=output_string
message_50=output_string
message_51=output_string
message_52=output_string
message_53=output_string
message_54=output_string
message_55=output_string
message_56=output_string
message_57=output_string
message_58=output_string
message_59=output_string
message_60=output_string
message_61=output_string
message_62=output_string
message_63=output_string
message_64=output_string
message_65=output_string
message_66=output_string
message_67=output_string
message_68=output_string
message_69=output_string
message_70=output_string
message_71=output_string
message_72=output_string
message_73=output_string
message_74=output_string
message_75=output_string
message_76=output_string
message_77=output_string
message_78=output_string
message_79=output_string
message_80=output_string
message_81=output_string
message_82=output_string
message_83=output_string
message_84=output_string
message_85=output_string
message_86=output_string
message_87=output_string
message_88=output_string
message_89=output_string
message_90=output_string
message_91=output_string
message_92=output_string
message_93=output_string
message_94=output_string
message_95=output_string
message_96=output_string
message_97=output_string
message_98=output_string
message_99=output_string
message_100=output_string
message_101=output_string
message_102=output_string
message_103=output_string
message_104=output_string
message_104=output_string
message_106=output_string
message_107=output_string
message_108=output_string
message_109=output_string
message_110=output_string
message_111=output_string
message_112=output_string
message_113=output_string
message_114=output_string
message_115=output_string
message_116=output_string
message_117=output_string
message_118=output_string
message_119=output_string
message_120=output_string
message_120=output_string
message_121=output_string
message_122=output_string
message_123=output_string
message_124=output_string
message_125=output_string
message_126=output_string
message_127=output_string
message_128=output_string
message_129=output_string
message_130=output_string
message_131=output_string
message_132=output_string
message_133=output_string
message_134=output_string
message_135=output_string
message_136=output_string
message_137=output_string
message_138=output_string
message_139=output_string
message_140=output_string
message_141=output_string
message_142=output_string
message_143=output_string
message_144=output_string
message_145=output_string
message_146=output_string
message_147=output_string
message_148=output_string
message_149=output_string
message_150=output_string
message_151=output_string
message_152=output_string
message_153=output_string
message_154=output_string
message_155=output_string
message_156=output_string
message_157=output_string
message_158=output_string
message_159=output_string
message_160=output_string
message_161=output_string
message_162=output_string
message_163=output_string
message_164=output_string
message_165=output_string
message_166=output_string
message_167=output_string
message_168=output_string
message_169=output_string
message_170=output_string
message_171=output_string
message_172=output_string
message_173=output_string
message_174=output_string
message_175=output_string
message_176=output_string
message_177=output_string
message_178=output_string
message_179=output_string
message_180=output_string
message_181=output_string
message_182=output_string
message_183=output_string
message_184=output_string
message_185=output_string
message_186=output_string
message_187=output_string
message_188=output_string
message_189=output_string
message_190=output_string
message_191=output_string
message_192=output_string
message_193=output_string
message_194=output_string
message_195=output_string
message_196=output_string
message_197=output_string
message_198=output_string
message_199=output_string
message_200=output_string
message_201=output_string
message_202=output_string
message_203=output_string
message_204=output_string
message_204=output_string
message_206=output_string
message_207=output_string
message_208=output_string
message_209=output_string
message_210=output_string
message_211=output_string
message_212=output_string
message_213=output_string
message_214=output_string
message_215=output_string
message_216=output_string
message_217=output_string
message_218=output_string
message_219=output_string
message_220=output_string
message_220=output_string
message_221=output_string
message_222=output_string
message_223=output_string
message_224=output_string
message_225=output_string
message_226=output_string
message_227=output_string
message_228=output_string
message_229=output_string
message_230=output_string
message_231=output_string
message_232=output_string
message_233=output_string
message_234=output_string
message_235=output_string
message_236=output_string
message_237=output_string
message_238=output_string
message_239=output_string
message_240=output_string
message_241=output_string
message_242=output_string
message_243=output_string
message_244=output_string
message_245=output_string
message_246=output_string
message_247=output_string
message_248=output_string
message_249=output_string
message_250=output_string
message_251=output_string
message_252=output_string
message_253=output_string
message_254=output_string
message_255=output_string
message_256=output_string
message_257=output_string
message_258=output_string
message_259=output_string
message_260=output_string
message_261=output_string
message_262=output_string
message_263=output_string
message_264=output_string
message_265=output_string
message_266=output_string
message_267=output_string
message_268=output_string
message_269=output_string
message_270=output_string
message_271=output_string
message_272=output_string
message_273=output_string
message_274=output_string
message_275=output_string
message_276=output_string
message_277=output_string
message_278=output_string
message_279=output_string
message_280=output_string
message_281=output_string
message_282=output_string
message_283=output_string
message_284=output_string
message_285=output_string
message_286=output_string
message_287=output_string
message_288=output_string
message_289=output_string
message_290=output_string
message_291=output_string
message_292=output_string
message_293=output_string
message_294=output_string
message_295=output_string
message_296=output_string
message_297=output_string
message_298=output_string
message_299=output_string


# variable filename
filename_1=test1.c # first File
filename_2=test2.c # second File
filename_3=test3.c # third File

# patch first File
sed -i 's/'$string_1'/'$message_1'/g' $filename_1
sed -i 's/'$string_2'/'$message_2'/g' $filename_1

# patch second File
sed -i 's/'$string_1'/'$message_1'/g' $filename_2

# patch second File
sed -i 's/'$string_1'/'$message_1'/g' $filename_3
